### ISSUE TITLE
Curators want to revise collection information for a private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#102]
**Story**

_Curators want to revise collection information for a private collection in response to updates or corrections from the collection owner._  

- Collection name
- Collection description
- Contact Name
- Contact Email

and add or delete:

- Optional Links

Also see [Publishers want to create a private collection for related dataset submissions](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/23).

The current links for the private collection and the regenerated CXG MUST be maintained. 

~**Note**: If there are changes to the collection information that are visible in the cellxgene explorer dataset drawer, then the related CXG needs to be re-generated because this information is currently embedded/duplicated in the CXG.~

**March 1**

We've agreed to remove all collection information from the dataset drawer so the CXG will not need to be regenerated.

---

**UX Design**

[Figma](https://www.figma.com/file/3C1RJrmCtKNBQffrAZoSFi/Private-Revisions)

**Comment by Bento007** [comment]
the CXG files generated are populated with information from the collection. If we make modifications to the collection then we must also update the CXG with the new information. The information used by the CXG is seen here  Project links and DOI![Screen Shot 2021-02-23 at 11.13.44 AM.png](https://images.zenhubusercontent.com/5a4d3418a016c5b034bbeac9/a0732ccf-9542-49e5-aad5-32416f4a9a48)

The same information on the Data portal. ![Screen Shot 2021-02-23 at 11.12.44 AM.png](https://images.zenhubusercontent.com/5a4d3418a016c5b034bbeac9/0ff7f40c-db79-4043-b7b9-19cd113f0640)

I propose we query the data portal for the collection information to display in the explorer rather than embedding it into the cxg.
