### ISSUE TITLE
Curators may update collection information in the private revision of a public collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#136]
**A curator MAY update collection information in the revision.**

This is similar to [Curators want to revise collection information for a private collection](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/102) with the additional requirement:

**A curator MUST easily understand the differences between the revision and the published collection.**

[Figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=441%3A122)

Pending question to @hthomas-czi on how edits to collection information are surfaced in the UX.

**Comment by hthomas-czi** [comment]
@brianraymor I have a [couple of concepts](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=535%3A164), but they strike me as unnecessarily busy. I'd like to keep in mind that less is often more. Displaying more information is not a purely additive process. As we add more visual clutter, any individual indicator becomes less clear and less meaningful. Ultimately we're building an interface to manage collections of datasets, not a word processor.  

I'd propose we only show the diff for datasets unless we hear from users that it's confusing or otherwise less usable.

**Comment by brianraymor** [comment]
I take our point. I agree with one clarification - datasets and gene sets.

**Comment by brianraymor** [comment]
@hthomas-czi and I agree that no visual indicators are needed when the curator changes collection information. Closing since there's no additional implementation required.
