### ISSUE TITLE
cellxgene offers a consistent and seamless experience for consumers

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#143]
This is a placeholder epic for a set of related prototypes to improve interactions between the portal and explorer, ensuring that the experience is seamless to a data consumer. In other words, we did not _ship the org_.

---

Based on a suggestion from @seve, we're going to transition to plausible.io which will NOT require a cookie banner. 

 **~There SHOULD be a consistent cookie banner and experience based on _Onetrust_.~**

~Today, the cookie banners for portal and explorer use different styles for visuals and interaction. The banner for explorer is blocking, but the banner for portal is not. _Onetrust_ is also needed for geolocation related to GDPR for policies.~

---

**Other references**

Portals with separate tabs for datasets and visualizations:

- [Single Cell Portal](https://singlecell.broadinstitute.org/single_cell/study/SCP1/-single-nucleus-rna-seq-of-cell-diversity-in-the-adult-mouse-hippocampus-snuc-seq#s[…]e)
- [Endoderm Explorer](https://endoderm-explorer.com/)

**Comment by hthomas-czi** [comment]
> Data consumers MUST be able to easily discover and review all metadata for a dataset.

Just wanted to note that the Figma mocks show a redesign of the data drawer itself to improve layout which we may want to call out. 

Otherwise this looks good to me.

**Comment by ambrosejcarr** [comment]
I see in the [explorer](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=45%3A730) design linked in the _Data consumers MUST be able to easily discover the portal and other collections from cellxgene explorer_ section that the design shows the "dataset drop-down" navigation to other datasets in a collection instead of the breadcrumbs design pattern. The drop-down wasn't the main purpose of linking the mock, so I'm wondering if that decision has been made. 

I know in breadcrumbs there's an extra click (return to portal, _then_ click dataset desired) but I preferred the breadcrumbs flow because I am concerned that the dataset name alone won't have sufficient information to support informed decisions about which dataset to navigate to. The user decides on the dataset name and we've seen a few examples already where uninformative names have been used (e.g. tabula muris). I think users will be able to make better decisions about which dataset to pick if they have the metadata available.

**Comment by brianraymor** [comment]
One clarification - _Tabula Muris Senis_ is the collection name. An example dataset is _Bladder lumen — A single-cell transcriptomic atlas characterizes ageing tissues in the mouse._

The thought experiment is _Explore the entire collection instead of an individual dataset_  - that a consumer may be exploring the BICCN collection and want to easily visualize them without returning to the portal and selecting another.

**Comment by brianraymor** [comment]
Visualizing by collection may also be useful in the future if the portal returned a temporary(?) collection of search+filter results with datasets spanning multiple collections.
