### ISSUE TITLE
Documentation site is deployed using gitbooks. 

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#165]
Tasks:
* Ensure docs.cellxgene.cziscience.com is available for deployment
* Deploy gitbooks documentation to that URL

Notes:
* Information on how to make a subdomain available for deployment and how to deploy gitbooks to an available subdomain is documented [here](https://docs.gitbook.com/hosting/custom-domains).

**Comment by atolopko-czi** [comment]
Do I need to be invited to a gitbook org? How do I gain access to gitbook?

**Comment by atolopko-czi** [comment]
If my understanding is correct, this redirect will only work for production, and not for dev/rdev/staging envs, since the custom domain that we'll need to configure on gitbooks.io identifies the subdomain from whence the request originated. For prod this will be `docs.cellxgene.cziscience.com`, but if the other envs' link are different I don't think this will work. 

For the other deploy environments, I suppose we could have them link to the direct github.io URL: https://chanzuckerberg.gitbook.io/cellxgene-documentation/.

**Comment by atolopko-czi** [comment]
Confirmed that gitbooks custom url feature works as expected, using a private domain and private gitbooks site.

**Comment by atolopko-czi** [comment]
Done. `docs.cellxgene.cziscience.com` now displays the gitbooks.io documentation correctly.
