### ISSUE TITLE
Update portal data model to associate all obs columns with an organism

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell#215]
Currently, only development_stage has an ontology that is specific to the organism. (And ethnicity is a NA for Mus Musculus).

In part to support multi-organism datasets, all obs fields should have some form of relation to an organism type.

The expectation is that a filter by tissue should result in results specific to the organism related to said tissue and not any other organism(s) present in the dataset containing the filtered tissue:

> The Homo sapiens data includes diseaseA and tissueA. The Mus musculus data includes diseaseB and tissueB. This is displayed in the cellxgene data portal as a dataset with columns:
>
> #### Organism
>Homo sapiens
Mus musculus
>
> #### Tissue
>tissueA
tissueB
>
> #### Disease
>diseaseA
diseaseB
>
>If a data consumer filters for Homo sapiens AND disease B, this dataset should not match. If a data consumer filters for Mus musculus AND tissueA, this dataset should not match.

**Comment by brianraymor** [comment]
Closing per **July 27 Refinement**: We agreed to continue to model organism as a dataset property rather than a observation property which may return false positives during search and filter. @maniarathi to provide a schedule for a re-design of the data model to support indexing of observations to enable accurate search+filter and dataset fabrication where a consumer requests the fabrication of a new dataset consisting of slices from one or more datasets that met the search+filter criteria.
