### ISSUE TITLE
Publishers must accept data submission policy before adding datasets to a collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#22]
**Story**

_Publishers must accept the CZI data submission policy before adding datasets to a collection_.

**Final Policy:**

-  _I give CZI permission to display, distribute, and create derivative works (e.g. visualizations) of this data for purposes of offering the cellxgene portal, and I have the authority to give this permission._

-  _It is my responsibility to ensure that this data is not identifiable. In particular, I commit that I will remove any [direct personal identifiers](https://docs.google.com/document/d/1nlUuRiQ8Awo_QsiVFi8OWdhGONjeaXE32z5GblVCfcI/edit) in the metadata portions of the data, and that CZI may further contact me if it believes more work is needed to de-identify it._ 

- _If I choose to publish this data **publicly** on the cellxgene portal, I understand that (1) anyone will be able to access it subject to a CC-BY license, meaning they can download, share, and use the data without restriction beyond providing attribution to me and (2) the Collection details I’ve provided above (collection name, description, and my contact information) will be made public on the cellxgene portal too._

- _I understand that I have the ability to delete my data from the cellxgene portal if I later change my mind. This will not undo any prior downloads or shares of my data._

**Comment by brianraymor** [comment]
During August 16 Refinement - @ambrosejcarr asked whether:

_I give **CZI** permission to use, display and create derivative works (e.g. visualizations) of this Data for purposes of offering the Cellxgene Public Portal, and I have the authority to give this permission._

needs to be extended to third party consumers downloading datasets for analysis.

**Comment by brianraymor** [comment]
August 31 - Requested an update from **Trust**.

**Comment by shawnliu03** [comment]
Hey Brian,

Following up here:

- Updated Direct Identifiers link (I couldn't edit old one so created a new copy): https://docs.google.com/document/d/1sboOmbafvMh3VYjK1-3MAUt0I13UUJfkQseq8ANLPl8/edit

**Updated language for Researcher Attestation:**

- I give CZI permission to use, display and create derivative works (e.g. visualizations) of this Data for purposes of offering the Cellxgene Public Portal, and I have the authority to give this permission.
- It is my responsibility to ensure that this Data is not identifiable. In particular, I commit that I will remove any [direct personal identifiers](https://docs.google.com/document/d/1sboOmbafvMh3VYjK1-3MAUt0I13UUJfkQseq8ANLPl8/edit) in the metadata portions of the Data, and that CZI may further contact me if it believes more work is needed to de-identify it.
- If I choose to publish this data publicly, I understand that anyone with access to Cellxgene will be able to access it subject to a CC-BY license, meaning they can download, share, and adapt the data without restriction beyond providing attribution to me.

**Comment by ambrosejcarr** [comment]
CC-BY is the license that was adopted by the DCP, but I am concerned it will produce problems for data re-use, and I believe it to be more restrictive than the use agreements for public archives. GEO [dodges the question a bit](https://www.ncbi.nlm.nih.gov/geo/info/disclaimer.html), but [the ENA](https://www.ebi.ac.uk/ena/browser/about/policies) is quite permissive. I would prefer we use lighter-weight means than licensing to enforce proper attribution of data donors, and request data in CC0. 

In particular, I am concerned that integration of multiple datasets will result in significant license stacking (all original licenses must be linked). This becomes worse if users then wish to integrate organs which are themselves composed of integrated sets of primary data. It seems better to design our software to automate citing (which meets the same user need) rather than do that _and_ add the enforcement of a license.

**Comment by brianraymor** [comment]
Pinged @shawnliu03 to review the[ comment](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/22#issuecomment-687315474) above.

**Comment by brianraymor** [comment]
Per the September 29 refinement for self-publication, we agreed that attestation should occur in the **Create Collection** flow rather than the **Add Dataset** flow.  Moving to _Publishers want to create a private collection of related dataset submissions_.

**Comment by shawnliu03** [comment]
Hi @ambrosejcarr and @brianraymor -- thanks for your patience. 

I'm OK with CC0 (do anything, no restrictions) instead of CC-BY (do anything, but give me attribution by citing to me), but want to call out one point and ask one question about our view on citations.

- The reason GEO dodges this is because not all authors uploading to GEO will be able to give maximal downstream rights because their institutions/local law may not let them. That'll be the same with cellxgene. This (e.g. cxg asks you to give cc0 rights for data, but your institution won't allow you to give such permissive rights) is not a reason to avoid CC0, but rather is something I just want to flag as an inherent tension in our clickthrough.
- Do I take the CC0 request here to also mean that's our stance vis-a-vis our own site if people pull data from it? That is, if someone takes datasets from cxg and then writes papers or publishes cool analyses, do we want/expect them to cite to cxg the tool?

**Comment by ambrosejcarr** [comment]
Hi @shawnliu03  

Thank you for the analysis of the GEO use case. What are our options for dealing with the "Geo problem" in cellxgene? Refuse to take the data? Take it without a license and warn the users somehow?

Our community wants the protection of CC-BY _in spirit_ and we will likely implement software solutions that enable easy citation of data that are downloaded for re-use. As an example, each cell could carry a pointer to a DOI, which would enable groups to rapidly identify all the publications they should cite. We will also generate documentation that discloses our expectations: "it is good practice to cite authors when you use their data, and here's how we make it easy...". In practice CC-BY is impractical for the reasons I stated in my earlier comment.

> Do I take the CC0 request here to also mean that's our stance vis-a-vis our own site if people pull data from it? That is, if someone takes datasets from cxg and then writes papers or publishes cool analyses, do we want/expect them to cite to cxg the tool?

Correct -- no _expectation_ that cellxgene will receive citations. Our MIT license is an even stronger statement of this. However, we _are_ planning a publication and may put an understated "here's how to cite cellxgene if you want to" point in the documentation somewhere. In my experience, some authors will want to cite it, even though we have no expectation.

**Comment by brianraymor** [comment]
@shawnliu03 - per the October 27 Trust XFN - to close on language for:

1. License
2. The required Contact (Name and Email) when a collection is created and published. The Contact is the point of contact for questions or PII reports for the datasets in a public collection.

**Comment by brianraymor** [comment]
@shawnliu03 - We met with curators from Stanford on November 3. One suggestion that they made related to the data submission policy was to make it clear to publishers that they would be able to withdraw/delete public (published) Collections.

**Comment by shawnliu03** [comment]
Thanks @brianraymor and @ambrosejcarr for helpful discussion and context here. I started a slack thread on CC-BY vs CC0 with Brian, Ambrose, Arathi because I want to make sure we're aligned on consequences of CC0.

Thanks, also for the Stanford data point. Given above, how about the below updated language:

- I give CZI permission to display, distribute, and create derivative works (e.g. visualizations) of this Data for purposes of offering the Cellxgene Public Portal, and I have the authority to give this permission.

- It is my responsibility to ensure that this Data is not identifiable. In particular, I commit that I will remove any [direct personal identifiers](https://docs.google.com/document/d/1sboOmbafvMh3VYjK1-3MAUt0I13UUJfkQseq8ANLPl8/edit) in the metadata portions of the Data, and that CZI may further contact me if it believes more work is needed to de-identify it.

- If I choose to publish this data publicly via the Cellxgene Public Portal, I understand that (1) anyone with access to Cellxgene will be able to access it subject to a [CC-BY or CC0 license, meaning they can download, share, and use the data without restriction beyond providing attribution to me. --> final language pending Slack discussion] and (2) the Collection details I've provided above (collection name, description, and my contact info) will be made public on Cellxgene too.

- I understand that I have the ability to unpublish data if I later change my mind. Such unpublishing will make the data no longer public on Cellxgene, but it will not undo any prior uses, shares, or downloads of my data.

**Comment by maniarathi** [comment]
Closed out the conversation with Shawn on the legalese. Here's the final version:

- I give CZI permission to display, distribute, and create derivative works (e.g. visualizations) of this Data for purposes of offering the Cellxgene Public Portal, and I have the authority to give this permission.
- It is my responsibility to ensure that this Data is not identifiable. In particular, I commit that I will remove any direct personal identifiers in the metadata portions of the Data, and that CZI may further contact me if it believes more work is needed to de-identify it.
- If I choose to publish this data publicly via the Cellxgene Public Portal, I understand that (1) anyone with access to Cellxgene will be able to access it subject to a CC-BY license, meaning they can download, share, and use the data without restriction beyond providing attribution to me and (2) the Collection details I’ve provided above (collection name, description, and my contact info) will be made public on Cellxgene too.
- I understand that I have the ability to unpublish data if I later change my mind. Such unpublishing will make the data no longer public on Cellxgene, but it will not undo any prior uses, shares, or downloads of my data.

**Comment by maniarathi** [comment]
The new wording has landed in prod, so closing.
