### ISSUE TITLE
Add a Github Actions job for rdev

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell#253]
Developers might prefer to push the code to a branch and have it automatically deployed to rdev. These steps might work:

1. Create a GHA job in both the explorer and portal
2. Hook the job to any `rdev/stack-name` branches
3. The job will clone the 3 repos `single-cell-{infra,data-portal,explorer}`, and checkout the correct branches
4. The job will `cd` to the infra repo and call the `happy` cli with the right paths
5. Add or update documentation for the new rdev behavior, in both portal and explorer repo's `REMOTE_DEV.md` files (add new file to explorer).  [Or should we now consider a single team-wide "Dev & Operations" doc?]

**Comment by atolopko-czi** [comment]
@ebezzi Maybe an alternate approach is to create a GHA job in the `single-cell-infra` repo (rather than individual portal/explorer repos), and have that do the `git checkout` of each repo, then build and deploy.  This would similarly move the repos' builds into GHA, but do it all at once.  We know this works locally, so it should work fine in GHA.

**Comment by atolopko-czi** [comment]
@ebezzi ok to close now?
