### ISSUE TITLE
Update cellxgene branding

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#309]
2022-07-27 UPDATE

@karenliang0 went through the Docs Site as well as the overall CellxGene Discover site to find all the locations where the brand name needed to be changed.

The Docs site changes are enumerated in [this document](https://docs.google.com/document/d/1N-xicGI6N9BqWrgg-kTTMPD8PZuSTFx4OudDZLP2LTY/edit).

All other changes are enumerated in [this document](https://docs.google.com/document/d/1DNnZhUrcLNyg95D0GZx-CR7WvE9Tzf0UkJ_KQrN5lp4/edit#).

--
~[This document](https://docs.google.com/document/d/1N-xicGI6N9BqWrgg-kTTMPD8PZuSTFx4OudDZLP2LTY/edit#) carries information on the rebranding work that will need to be done. We will execute the rebranding in phases. This issue and document covers phase 1.~

~Phase 1:~
~* Roll out new name & icon across product suite (7/25-7/29)~

~Phase 2:~
~* Create redirects from other owned URLs (To be planned)~

~Phase 3:~
~* Plan migration to new URL (To be planned)~

**Comment by maniarathi** [comment]
Update from Slack thread. @karenliang0 will take on the work to replace the logos and texts throughout our site with our rebranded logo, including products (which also includes the TOS and privacy policy pages), docs, and public-facing Github documentation (READMEs, etc.). @brianraymor will replace the schemas. @seve is responsible for reviewing all the changes and will be available for support as needed.

Timeline:
July 25 - 26, (@karenliang0 out 27 - 29), Aug 1: document changes needed (changes can start being made for doc site since those are noted already in linked doc)
July 25 - Aug 2: make changes
Aug 3 - 4: review changes
Aug 5: change any outstanding items we find during review

**Comment by ashin-czi** [comment]
cellxgene PR #2550 is approved but running into unit-test stage errors. Might need some guidance on who to reach out to for this

**Comment by ashin-czi** [comment]
Just waiting for cellxgene repo to have unit-test stage errors resolved
https://github.com/chanzuckerberg/cellxgene/runs/7792436106?check_suite_focus=true

**Comment by metakuni** [comment]
@ashin-czi : Are the tests passing now?

**Comment by ashin-czi** [comment]
Yup! Alec made a fix for the unit tests so the PR for this is now merged!

**Comment by ashin-czi** [comment]
Now ready for staging
