### ISSUE TITLE
Complete pilot and write up findings and make GO/No GO decision

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell#402]

**Comment by norbid** [comment]
See [final feasibility report](https://docs.google.com/document/d/1Y8bKDYWGv9YY5_pMGAtdfclEZ9nc2MPBb_DkV1qo2T8/edit#heading=h.7ja72ubjoask). 

Recommendation:
This project is feasible to accomplish within H2 of 2023 to Q1 of 2024. The time and cost have been substantially lowered by keeping it in-house and partnering with a motivated academic collaborator, rather than developing it ourselves or attempting to encourage development via grant funding. At this advanced stage and momentum of the project, attempting to incentivize the development of other tools is unlikely to attract interest. The compute time has been lowered to reasonable run times with the optimized pipeline developed by our academic partner. CZI is well-positioned to continue to support the momentum and scale up with our collaborator. The value of the project for greater functionality and utility for CELLxGENE is high. The recommendation is to continue to move forward and scale up the project by running the optimized tool on the full data corpus and splitting the datasets between the CZI internal team and our academic collaborator, and assisting our collaborator in setting up [SCAI](https://scai.readthedocs.io/en/latest/index.html) as a pipeline that we can point data submitters to for them to infer ancestry and provide that metadata.
