### ISSUE TITLE
Redirect from old docs site to new docs site

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#448]
The old gitbook docs deployment should not be accessible. 

https://docs.cellxgene.cziscience.com/

Context: https://github.com/chanzuckerberg/single-cell-data-portal/issues/3510

- [ ] Update terraform
- [ ] Tear down Gitbook AFTER the above TF change in prod

**Comment by tihuan** [comment]
I think we need just to point

https://github.com/chanzuckerberg/single-cell-infra/blob/6cf4989854d3972ec927f74e97f0f7134072239f/terraform/accounts/single-cell-prod/cellxgene_cziscience_zone.tf#L9 to the new doc site URL (https://cellxgene.cziscience.com/docs)

Will work on it now

**Comment by tihuan** [comment]
Actually since we don't want to keep Gitbook around, we'd need to create a simple static site to redirect

**Comment by tihuan** [comment]
Asking Infra for TF module example now

https://chanzuckerbergteam.slack.com/archives/C94RQ5SBV/p1687359363107569

**Comment by tihuan** [comment]
@abiju-czi from Infra will likely create a TF module to add an ELB to redirect docs.cellxgene.cziscience.com -> cellxgene.cziscience.com/docs

Steps:

1. Route53 CNAME record docs.cellxgene.cziscience.com points to the new ELB
2. New ELB needs cert for docs.cellxgene.cziscience.com + a redirect to cellxgene.cziscience.com/docs
3. Apply TF change in prod
4. Voila! 
5. Delete Gitbook account after everything works for a few days

**Comment by tihuan** [comment]
Will check in with Alex On Friday!

**Comment by tihuan** [comment]
Synced with Alex! 

He talked to his team about different redirect options and they realized that doing redirect via ALB/ELB would be more costly than using a public S3 static site. 

HOWEVER, public S3 static site has its own AWS tenant and AWS role, so that would introduce a brain split in terms of where related AWS configs would live (single-cell-prod vs. single-cell-public)

The solution we landed on is:
1. Update Route53 Record docs.cellxgene.cziscience.com to point to cellxgene.cziscience.com's CloudFront (instead of gitbook doc site)
2. cellxgene.cziscience.com CloudFront will then forward the request to the front end server cluster for Next.js to handle the request
3. Next.js will read the request and respond with a permanent redirect to cellxgene.cziscience.com/docs

Outstanding question:
1. In order for the front end server to handle docs.cellxgene.cziscience.com requests, `happy` needs to support cellxgene.cziscience.com CloudFront to be on multiple subdomains (e.g., cellxgene.cziscience.com AND docs.cellxgene.cziscience.com) -- this will be a question for `happy` team

**Comment by tihuan** [comment]
Reached out to Happy:

https://chanzuckerbergteam.slack.com/archives/C01C310V70X/p1687545310250469

**Comment by tihuan** [comment]
Figured out a path forward after consulting @abiju-czi and @ebezzi 💡

1. Create a new repo to use its Git Page to redirect request from `docs.cellxgene.cziscience.com` to `cellxgene.cziscience.com/docs`
2. Gitpage will just be a blank page with a metatag to redirect to cellxgene.cziscience.com/docs
2. Update Route53 to point docs.cellxgene.cziscience.com to the new Git page
3. Once this change is deployed, remove Gitbook hosting
