### ISSUE TITLE
feat(schema4): remove suffix logic in ontology_term_label function in ontology_labels.py

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell#525]

**Comment by nayib-jose-gloria** [comment]
NOTE: this should be done AFTER schema 4.0.0 migration. It is also not urgent as far as I understand, though it is good clean-up. Based on my scanning of this code, it'll be harmless albeit superfluous--even if it stays, it'll just be a no-op because it won't ever match for this suffix after migration because we're getting rid of it.

@atarashansky / @dsadgat

**Comment by nayib-jose-gloria** [comment]
^ but please correct me if that's misunderstanding how this works

**Comment by prathapsridharan** [comment]
@joyceyan @dsadgat @nayib-jose-gloria - For the same reason as https://github.com/chanzuckerberg/single-cell-data-portal/issues/6076 (and as @nayib-jose-gloria mentioned above), this ticket can be picked up after verifying that we have fully transitioned to schema-4.
