### ISSUE TITLE
feat(schema4): update ontology_term_label function in ontology_labels.py to appropriately handle multi-value strings

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell#528]
It appears with [schema 4](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5737), we now want to be able to support a comma-delimited list of strings for `self_reported_ethnicity`. We'll have to update [ontology_term_label](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/wmg/data/ontology_labels.py#L23-L44) to support a comma-delimited string. For example, if we receive `"HANCESTRO:0005,HANCESTRO:0014"` as the `ontology_term_id`, we should map this to `"European, Hispanic or Latin American"`

If there's a feature flag for this field update in schema 4, we should gate the change behind the flag.

**Comment by prathapsridharan** [comment]
Closing this PR because in a code review with @joyceyan @atarashansky on 10/30/2023, it was decided that we are _filtering out comma-delimited ethnicity term IDs_ from grouping and filtering if they are done by `self_reported_ethnicity_ontology_term_id`. 

This filtering work is the subject of this ticket: https://github.com/chanzuckerberg/single-cell/issues/596

Thus no translation of term ID to term label is needed for comma-delimited term IDs for `self_reported_ethnicity_ontology_term_id`
