### ISSUE TITLE
References to obsolete native cell must be addressed

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#611]
# Context

**Note: This is a placeholder epic for Dev to add child issues following an assessment of required changes.**

---

See [Update now-obsolete 'native cell' in schema](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/622) and [obsolete native cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000003). 

When the CL ontology is refreshed for schema 4.1 (February 2024), the code base must be reviewed for dependencies or references to the obsolete label or term. For example:

* [label in single-cell-data-portal](https://github.com/search?q=repo%3Achanzuckerberg%2Fsingle-cell-data-portal%20%22native%20cell%22&type=code)
* [term in single-cell-data-portal](https://github.com/search?q=repo%3Achanzuckerberg%2Fsingle-cell-data-portal+%22CL%3A0000003%22&type=code)
* [label in cellxgene-census](https://github.com/search?q=repo%3Achanzuckerberg%2Fcellxgene-census%20%22native%20cell%22&type=code)
* [term in cellxgene-census](https://github.com/search?q=repo%3Achanzuckerberg%2Fcellxgene-census+%22CL%3A0000003+%22&type=code)

CC: @metakuni @dsadgat @pablo-gar

**Comment by danieljhegeman** [comment]
@brianraymor it looks to me like we have two pieces of work for this epic:
1. Correct the places throughout out codebase where we reference the native cell term (such as the instances you've linked to in the data portal and the census), and
2. _Requirement:_ Permit `"unknown"` for both `cell_type_ontology_term_id` and `tissue_ontology_term_id`. _Implementation detail:_ add an array block for both places where `CL` is allowed under `ontologies:` in the schema definition yml similar to what is being done [here](https://github.com/chanzuckerberg/single-cell-curation/blob/1107d988dff667280ce15131c38b05ce25aa82a4/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L182-L183).

Please approve or comment otherwise when you get a chance 🙏

**Comment by danieljhegeman** [comment]
It's not immediately clear to me if this will require edits to the FE filter compute script(s).
